<?php
/*
$this->headTitle('Add Contact');

$this->mainMenu()->setActiveItemId('contacts');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Contacts'=>$this->url('contact'),
    'Add Contact'=>$this->url('contact', ['action'=>'add'])
]);
*/

$form->get('name')->setAttributes(['class'=>'form-control', 'placeholder'=>'name of the domain']);

// buttons
$form->get('cancel')->setAttributes(['class' => 'btn btn-outline-secondary', 'style' => 'margin-right:10px;']);
$form->get('save')->setAttributes(['class' => 'btn btn-primary', 'style' => 'margin-right:10px;']);
$form->get('save_and_edit')->setAttributes(['class' => 'btn btn-info', 'style' => 'margin-right:10px;']);

$form->prepare();
?>

<div class="container-fluid">

    <div class="row">

        <div class="col-12">

            <h1>Add Domain</h1>

            <p>
                Please fill out the following form and click the <i>Save</i> button or the <i>Save And Edit</i> to edit after the save.
            </p>

            <hr>

        </div>

    </div>

    <div class="row">

        <div class="col-md-6">

            <?= $this->form()->openTag($form); ?>

            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>
            </div>

            <?= $this->formElement($form->get('cancel')); ?>
            <?= $this->formElement($form->get('save')); ?>
            <?= $this->formElement($form->get('save_and_edit')); ?>

        </div>

        <div class="col-6">

            &nbsp;

        </div>

    </div>

</div>

<script>

    $(document).ready(function () {

        $('#name').focus();

    });

</script>
