<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('bootstrap-select/dist/css/bootstrap-select.min.css'))
            ->prependStylesheet($this->basePath('/DataTables/datatables.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('bootstrap-select/dist/js/bootstrap-select.min.js'))
            ->prependFile($this->basePath('js/fontawesome.js'))
            ->prependFile($this->basePath('/DataTables/datatables.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/popper.min.js')) // order is important
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
    </head>
    <body>
        <div class="container">

            <div class="row">

                <div class="col-12">

                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <a class="navbar-brand" href="/">Mailserver</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav">
                                <li class="nav-item active">
                                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/domain/index">Domain</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/user/index">User</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/alias/index">Alias</a>
                                </li>
                            </ul>
                        </div>
                    </nav>

                </div>

            </div>

            <div class="row" style="margin-top:20px;">

                <div class="col-12">

                    <?= $this->content ?>

                </div>

            </div>

            <div class="row" style="margin-top:20px;">

                <div class="col-12">

                    <hr>

                    <footer>
                        <p>&copy; 2019 - <?= date('Y') ?> by Tencorners, L.L.C. All rights reserved.</p>
                    </footer>

                </div>

            </div>

        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
