<div class="jumbotron">
    <div class="container-fluid">
        <div class="row">
            <div class="col-5">
                <img src="/img/email.jpg" height="200">
            </div>
            <div class="col-7">
                <h1>Mailserver</h1>
                Keeping track of domains, users, alias with a front end interface.
            </div>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Domain</h3>
            </div>
            <div class="panel-body d-flex flex-column" style="height:225px;"
                <p>
                    All of the domains that will be handled by this mail server.
                </p>

                <a style="width:125px;" class="btn btn-primary pull-right mt-auto" href="/domain/index">Domains &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col-md-4" >
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Users</h3>
            </div>
            <div class="panel-body d-flex flex-column" style="height:225px;">
                <p>
                    Keep track of users.  Create them, modify (including password resets) and remove from the system.
                </p>

                <a style="width:125px;" class="btn btn-primary pull-right mt-auto" href="/user/index">User &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Aliases</h3>
            </div>
            <div class="panel-body d-flex flex-column" style="height:225px;">
                <p>
                    Create relationships between users and virtual address.  Great for tracking spam and then turning off at some point in time.
                </p>

                <a style="width:125px;" class="btn btn-primary pull-right mt-auto" href="/alias/index">Alias &raquo;</a>
            </div>
        </div>
    </div>
</div>
